dependencies:
  - name: jenkins
    version: 0.8.9
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: nginx-ingress
    version: 0.8.4
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: kube-lego
    version: 0.1.11
    repository: https://kubernetes-charts.storage.googleapis.com
