jenkins:
  Persistence:
    #    Enabled: false
    #    ExistingClaim: 'build-mattermost-com-jenkins'
    Size: 10Gi
  Master:
    HostName: newbuild.local
    Image: local/jenkins-master
    #    ImageTag: latest
    #    ImagePullSecrets:
    #     - name: myregistrykey
    ImagePullPolicy: Never
    Ingress:
      Annotations:
        kubernetes.io/tls-acme: "false"
        kubernetes.io/ingress.class: nginx
        ingress.kubernetes.io/force-ssl-redirect: "false"
#      TLS:
#      - secretName: newbuild-tls
#        hosts:
#        - newbuild.local
    ServiceType: NodePort
    ServicePort: 8080
    InstallPlugins:
      - kubernetes
      - workflow-aggregator
      - credentials-binding
      - git
      - build-pipeline-plugin
      - github-branch-source
      - s3
      - active-directory
      - rebuild
        #kube-lego:
        #  config:
        #    LEGO_EMAIL: dev-ops@mattermost.com
        #    LEGO_URL: https://acme-v01.api.letsencrypt.org/directory
