jenkins:
  Persistence:
    Enabled: false
    ExistingClaim: 'build-mattermost-com-jenkins'
    Size: 100Gi
  Master:
    HostName: newbuild.mattermost.com
    Image: mmjenkins.azurecr.io/jenkins-master
    ImageTag: latest
    ImagePullSecrets:
        - name: myregistrykey
    ImagePullPolicy: Always
    Ingress:
      Annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: nginx
        ingress.kubernetes.io/force-ssl-redirect: "true"
      TLS:
      - secretName: newbuild-tls
        hosts:
        - newbuild.mattermost.com
    ServiceType: ClusterIP
    ServicePort: 8080
    InstallPlugins:
      - kubernetes
      - workflow-aggregator
      - credentials-binding
      - git
      - build-pipeline-plugin
      - github-branch-source
      - s3
      - active-directory
      - rebuild
kube-lego:
  config:
    LEGO_EMAIL: dev-ops@mattermost.com
    LEGO_URL: https://acme-v01.api.letsencrypt.org/directory
