apiVersion: v1
kind: PersistentVolume
metadata:
    name: build-mattermost-com-pv
spec:
    capacity:
        storage: "40Gi"
    accessModes:
        - "ReadWriteOnce"
    azureDisk:
        deskName: jenkins.vhd
        diskURI: 
