kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: build-mattermost-com-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 40Gi
